let data =  [
        {
            "id": 1,
            "Player": "CadeCunningham",
            "Team": "Oklahoma State",
            "G": 27,
            "GS": 26,
            "MPG": 35.4,
            "FG": 6.5,
            "FGA": 14.8,
            "FG%": 0.438,
            "2P": 4.2,
            "2PA": 9.1,
            "2P%": 0.461,
            "3P": 2.3,
            "3PA": 5.7,
            "3P%": 0.400,
            "FT": 4.9,
            "FTA": 5.8,
            "FT%": 0.846,
            "ORB": 0.7,
            "DRB": 5.5,
            "TRB": 6.2,
            "AST": 3.5,
            "STL": 1.6,
            "BLK": 0.8,
            "TOV": 4.0,
            "PF": 2.5,
            "PTS": 20.1
        },
        {
            "id": 2,
            "Player": "EvanMobley",
            "Team": "USC",
            "G": 33,
            "GS": 33,
            "MPG": 33.9,
            "FG": 6.0,
            "FGA": 10.3,
            "FG%": 0.578,
            "2P": 5.6,
            "2PA": 9.1,
            "2P%": 0.615,
            "3P": 0.4,
            "3PA": 1.2,
            "3P%": 0.300,
            "FT": 4.1,
            "FTA": 5.8,
            "FT%": 0.694,
            "ORB": 2.7,
            "DRB": 5.9,
            "TRB": 8.7,
            "AST": 2.4,
            "STL": 0.8,
            "BLK": 2.9,
            "TOV": 2.2,
            "PF": 1.8,
            "PTS": 16.4
        },
        {
            "id": 3,
            "Player": "JalenSuggs",
            "Team": "Gonzaga",
            "G": 30,
            "GS": 30,
            "MPG": 28.9,
            "FG": 5.2,
            "FGA": 10.3,
            "FG%": 0.503,
            "2P": 4.0,
            "2PA": 6.8,
            "2P%": 0.588,
            "3P": 1.2,
            "3PA": 3.5,
            "3P%": 0.337,
            "FT": 2.9,
            "FTA": 3.8,
            "FT%": 0.754,
            "ORB": 0.6,
            "DRB": 4.7,
            "TRB": 5.3,
            "AST": 4.5,
            "STL": 1.9,
            "BLK": 0.3,
            "TOV": 2.9,
            "PF": 2.6,
            "PTS": 14.4
        },
        {
            "id": 4,
            "Player": "JalenGreen",
            "Team": "G League Ignite",
            "G": 15,
            "GS": 15,
            "MPG": 32.0,
            "FG": 6.3,
            "FGA": 13.6,
            "FG%": 0.461,
            "2P": 4.2,
            "2PA": 7.9,
            "2P%": 0.529,
            "3P": 2.1,
            "3PA": 5.7,
            "3P%": 0.365,
            "FT": 1.9,
            "FTA": 2.3,
            "FT%": 0.829,
            "ORB": 0.5,
            "DRB": 3.5,
            "TRB": 4.1,
            "AST": 2.8,
            "STL": 1.5,
            "BLK": 0.3,
            "TOV": 2.7,
            "PF": 1.7,
            "PTS": 17.9
        },
        {
            "id": 5,
            "Player": "JonathanKuminga",
            "Team": "G League Ignite",
            "G": 13,
            "GS": 13,
            "MPG": 32.8,
            "FG": 5.5,
            "FGA": 14.3,
            "FG%": 0.387,
            "2P": 4.3,
            "2PA": 9.3,
            "2P%": 0.463,
            "3P": 1.2,
            "3PA": 5.0,
            "3P%": 0.246,
            "FT": 2.3,
            "FTA": 3.7,
            "FT%": 0.625,
            "ORB": 1.2,
            "DRB": 6.0,
            "TRB": 7.2,
            "AST": 2.7,
            "STL": 1.0,
            "BLK": 0.8,
            "TOV": 2.6,
            "PF": 2.1,
            "PTS": 15.8
        }
    ];